(() => {
"use strict";
const SUPABASE_URL="https://ubbajcuhvckhygnbhdhk.supabase.co";
const SUPABASE_KEY="sb_publishable_ZRAm3yLxh4d7ZhFl4MWwBA_RgAuXiHV";
const { createClient } = window.supabase;
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});

const STEP_DEFS=[
  ["来店","arrival_at"],["説明","explanation_at"],["前菜","starter_at"],["鍋温め","pot_warm_at"],
  ["鍋作り終わり","pot_finish_at"],["山椒","sansho_at"],["あく取り・スープ","soup_at"],
  ["〆の発注","closing_order_at"],["〆作り終わり","closing_finish_at"],["あがりおしぼり","oshibori_at"],["会計","checkout_at"]
];
const COL_TO_LABEL=Object.fromEntries(STEP_DEFS.map(([l,c])=>[c,l]));
const OP_QUEUE_KEY="service-time-v2-offline-queue";
const CACHE_KEY="service-time-v2-cache";
const JST_DATE=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const timeFmt=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",hour12:false});
const dateFmt=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"long",day:"numeric",weekday:"short"});
const body=document.getElementById("body"),cardList=document.getElementById("cardList"),saveState=document.getElementById("saveState");
let groups=[],history=[],channel=null,currentDetailId=null,currentDate=JST_DATE(),isSyncing=false;
let linkRepresentative=null,linkSelected=new Set();

function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function fmtTime(v){return v?timeFmt.format(new Date(v)):""}
function elapsedFrom(v){if(!v)return"--:--:--";const sec=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/1000));return String(Math.floor(sec/3600)).padStart(2,"0")+":"+String(Math.floor(sec%3600/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}
function tableLabel(g){return [...g.linked_tables].sort((a,b)=>a-b).join("・")+"卓"}
function groupForTable(n){return groups.find(g=>(g.linked_tables||[]).includes(n))}
function isRepresentative(g,n){return g && g.representative_table===n}
function hasService(g){return STEP_DEFS.some(([,c])=>!!g[c])}
function isLate(g){if(!g?.reservation_time||g.arrival_at||g.checkout_at)return false;const hm=String(g.reservation_time).slice(0,5).split(":").map(Number);const now=new Date();const jp=new Date(now.toLocaleString("en-US",{timeZone:"Asia/Tokyo"}));const r=new Date(jp);r.setHours(hm[0],hm[1],0,0);return jp>=r}
function potWarn(g){return !!(g?.pot_warm_at&&!g.pot_finish_at&&!g.checkout_at&&(Date.now()-new Date(g.pot_warm_at).getTime()>=330000))}
function twoHour(g){return !!(g?.arrival_at&&!g.checkout_at&&(Date.now()-new Date(g.arrival_at).getTime()>=7200000))}
function currentAction(g){let best=null;for(const [label,col] of STEP_DEFS){if(g?.[col]){const t=new Date(g[col]).getTime();if(!best||t>best.t)best={label,t}}}return best?.label||"—"}
function labelHtml(step){return step.replace("鍋作り終わり","鍋作り<br>終わり").replace("あく取り・スープ","あく取り<br>・スープ").replace("〆作り終わり","〆作り<br>終わり").replace("あがりおしぼり","あがり<br>おしぼり")}
function cacheLocal(){localStorage.setItem(CACHE_KEY,JSON.stringify({date:currentDate,groups,history}))}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem(CACHE_KEY)||"null");if(x?.date===currentDate){groups=x.groups||[];history=x.history||[]}}catch{}}
function getQueue(){try{return JSON.parse(localStorage.getItem(OP_QUEUE_KEY)||"[]")}catch{return[]}}
function setQueue(q){localStorage.setItem(OP_QUEUE_KEY,JSON.stringify(q));showConnection()}
function queue(op){const q=getQueue();q.push(op);setQueue(q)}
function showConnection(){const offline=!navigator.onLine||getQueue().length>0;document.getElementById("offlineBanner").classList.toggle("show",offline);if(saveState)saveState.textContent=offline?"同期待ち":"同期済み"}
function localPatch(id,patch){const g=groups.find(x=>x.id===id);if(g)Object.assign(g,patch);cacheLocal();renderAll()}

async function ensureAuth(){const {data:{session}}=await sb.auth.getSession();if(!session){const {error}=await sb.auth.signInAnonymously();if(error)throw error}}
async function seedIfNeeded(){const {data,error}=await sb.from("service_groups").select("*").eq("business_date",currentDate);if(error)throw error;if(data.length===0){const rows=Array.from({length:9},(_,i)=>({business_date:currentDate,representative_table:i+1,linked_tables:[i+1]}));const ins=await sb.from("service_groups").insert(rows);if(ins.error)throw ins.error}}
async function loadCloud(){if(!navigator.onLine)return;const [g,h]=await Promise.all([sb.from("service_groups").select("*").eq("business_date",currentDate),sb.from("service_history").select("*").eq("business_date",currentDate).order("archived_at",{ascending:false})]);if(g.error)throw g.error;if(h.error)throw h.error;groups=g.data||[];history=h.data||[];cacheLocal();renderAll()}
async function subscribeRealtime(){if(channel)await sb.removeChannel(channel);channel=sb.channel("service-time-"+currentDate).on("postgres_changes",{event:"*",schema:"public",table:"service_groups",filter:"business_date=eq."+currentDate},()=>loadCloud().catch(()=>{})).on("postgres_changes",{event:"*",schema:"public",table:"service_history",filter:"business_date=eq."+currentDate},()=>loadCloud().catch(()=>{})).subscribe()}
async function purgeOldDays(){await Promise.all([sb.from("service_groups").delete().lt("business_date",currentDate),sb.from("service_history").delete().lt("business_date",currentDate)])}
async function init(){loadLocal();renderAll();showConnection();try{await ensureAuth();await purgeOldDays();await seedIfNeeded();await flushQueue();await loadCloud();await subscribeRealtime();showConnection()}catch(e){console.error(e);showConnection()}}

async function recordStep(g,col){
  if(g[col])return cancelStep(g,col);
  const stamp=new Date().toISOString();localPatch(g.id,{[col]:stamp});const op={type:"record",id:g.id,col,stamp};
  if(!navigator.onLine){queue(op);return}
  try{
    let q=await sb.rpc("record_service_step",{p_group_id:g.id,p_column:col,p_step_time:stamp});
    if(q.error && /function .*record_service_step.* does not exist/i.test(q.error.message||"")){
      q=await sb.from("service_groups").update({[col]:stamp}).eq("id",g.id).is(col,null);
    }
    if(q.error)throw q.error;await loadCloud();showConnection();
  }catch(e){queue(op);showConnection()}
}
async function cancelStep(g,col){const label=COL_TO_LABEL[col];if(!confirm("「"+label+"」の記録を取り消しますか？"))return;localPatch(g.id,{[col]:null});const op={type:"cancel",id:g.id,col};if(!navigator.onLine){queue(op);return}try{const q=await sb.from("service_groups").update({[col]:null}).eq("id",g.id);if(q.error)throw q.error;showConnection()}catch(e){queue(op);showConnection()}}
async function updateReservation(g,val){const patch={reservation_time:val||null};localPatch(g.id,patch);const op={type:"reservation",id:g.id,val:val||null};if(!navigator.onLine){queue(op);return}try{const q=await sb.from("service_groups").update(patch).eq("id",g.id);if(q.error)throw q.error;showConnection()}catch(e){queue(op)}}
async function flushQueue(){if(isSyncing||!navigator.onLine)return;isSyncing=true;let q=getQueue(),left=[];for(const op of q){try{let r;if(op.type==="record"){r=await sb.rpc("record_service_step",{p_group_id:op.id,p_column:op.col,p_step_time:op.stamp});if(r.error&&/function .*record_service_step.* does not exist/i.test(r.error.message||""))r=await sb.from("service_groups").update({[op.col]:op.stamp}).eq("id",op.id).is(op.col,null)}else if(op.type==="cancel")r=await sb.from("service_groups").update({[op.col]:null}).eq("id",op.id);else if(op.type==="reservation")r=await sb.from("service_groups").update({reservation_time:op.val}).eq("id",op.id);else continue;if(r.error)throw r.error}catch(e){left.push(op)}}setQueue(left);isSyncing=false;if(!left.length)await loadCloud().catch(()=>{})}

async function nextGroup(g){const label=tableLabel(g);if(!confirm(label+"を次の組に切り替えますか？\n現在の記録は履歴に保存されます。"))return;if(!navigator.onLine){alert("「次の組」は通信復旧後に操作してください。接客記録はオフライン中も保存できます。");return}const hasAny=!!g.reservation_time||hasService(g);if(hasAny){const hist={business_date:currentDate,representative_table:g.representative_table,linked_tables:g.linked_tables,reservation_time:g.reservation_time,arrival_at:g.arrival_at,explanation_at:g.explanation_at,starter_at:g.starter_at,pot_warm_at:g.pot_warm_at,pot_finish_at:g.pot_finish_at,sansho_at:g.sansho_at,soup_at:g.soup_at,closing_order_at:g.closing_order_at,closing_finish_at:g.closing_finish_at,oshibori_at:g.oshibori_at,checkout_at:g.checkout_at};const a=await sb.from("service_history").insert(hist);if(a.error){alert("履歴保存に失敗しました");return}}const d=await sb.from("service_groups").delete().eq("id",g.id);if(d.error){alert("切り替えに失敗しました");return}const rows=[...g.linked_tables].sort((a,b)=>a-b).map(n=>({business_date:currentDate,representative_table:n,linked_tables:[n]}));const i=await sb.from("service_groups").insert(rows);if(i.error){alert("卓の再作成に失敗しました");return}currentDetailId=null;await loadCloud()}
async function resetToday(){if(!confirm("今日のすべての記録をリセットしますか？\n1〜9卓の記録と当日履歴が削除されます。"))return;if(!navigator.onLine){alert("今日のリセットはオンライン時のみ操作できます。");return}await sb.from("service_history").delete().eq("business_date",currentDate);await sb.from("service_groups").delete().eq("business_date",currentDate);await seedIfNeeded();currentDetailId=null;await loadCloud()}

function openLinkDialog(repIdFromMobile=null){linkRepresentative=repIdFromMobile;const rep=groups.find(g=>g.id===repIdFromMobile);linkSelected=new Set(rep?.linked_tables||[]);renderLinkChoices();document.getElementById("linkDialog").showModal()}
function renderLinkChoices(){const box=document.getElementById("linkChoices");box.innerHTML="";for(let n=1;n<=9;n++){const g=groupForTable(n),b=document.createElement("button");b.type="button";b.className="choice";b.textContent=n+"卓";if(!g)b.disabled=true;const repChosen=linkRepresentative&&g?.id===linkRepresentative;if(repChosen||linkSelected.has(n))b.classList.add("selected");b.onclick=()=>{if(!linkRepresentative){if(!g||hasService(g))return alert("この卓は現在連結できません。");linkRepresentative=g.id;linkSelected=new Set(g.linked_tables||[n])}else{const rep=groups.find(x=>x.id===linkRepresentative);if(g?.id===rep?.id)return;if(!g||g.linked_tables.length>1||hasService(g))return alert("この卓は現在連結できません。");if(linkSelected.has(n))linkSelected.delete(n);else linkSelected.add(n)}renderLinkChoices()};box.appendChild(b)}const rep=groups.find(x=>x.id===linkRepresentative);if(rep&&!linkSelected.has(rep.representative_table))linkSelected.add(rep.representative_table);document.getElementById("linkInstructions").textContent=rep?("代表卓："+rep.representative_table+"卓　連結する卓を選択"):"最初に代表卓を選んでください。";const warnings=[];if(rep){for(const n of linkSelected){const g=groupForTable(n);if(g&&g.id!==rep.id&&g.reservation_time)warnings.push(n+"卓の予約 "+String(g.reservation_time).slice(0,5)+" は使用されなくなります。")}}document.getElementById("linkWarning").textContent=warnings.join(" ")}
async function confirmLink(){const rep=groups.find(x=>x.id===linkRepresentative);if(!rep||linkSelected.size<2)return alert("連結する卓を2卓以上選んでください。");if(!navigator.onLine)return alert("卓の連結はオンライン時のみ操作できます。");const ids=[];for(const n of linkSelected){const g=groupForTable(n);if(g&&g.id!==rep.id&&!ids.includes(g.id))ids.push(g.id)}const all=[...linkSelected].sort((a,b)=>a-b);const reserved=ids.map(id=>groups.find(g=>g.id===id)).filter(g=>g?.reservation_time);let msg=all.join("・")+"卓を連結します。\n代表卓："+rep.representative_table+"卓";for(const g of reserved)msg+="\n"+g.representative_table+"卓の予約 "+String(g.reservation_time).slice(0,5)+" は使用されなくなります。";if(!confirm(msg))return;const u=await sb.from("service_groups").update({linked_tables:all}).eq("id",rep.id);if(u.error)return alert("連結に失敗しました");if(ids.length){const d=await sb.from("service_groups").delete().in("id",ids);if(d.error)return alert("連結に失敗しました")}document.getElementById("linkDialog").close();currentDetailId=rep.id;await loadCloud()}
async function unlinkGroup(g){if(hasService(g))return alert("接客記録が始まった後は連結解除できません。「次の組」で自動解除されます。");if(!confirm(tableLabel(g)+"の連結を解除しますか？"))return;if(!navigator.onLine)return alert("連結解除はオンライン時のみ操作できます。");const keep=g.representative_table,others=g.linked_tables.filter(n=>n!==keep);const u=await sb.from("service_groups").update({linked_tables:[keep]}).eq("id",g.id);if(u.error)return alert("解除に失敗しました");if(others.length){const ins=await sb.from("service_groups").insert(others.map(n=>({business_date:currentDate,representative_table:n,linked_tables:[n]})));if(ins.error)return alert("解除に失敗しました")}await loadCloud()}

function renderDesktop(){body.innerHTML="";for(let n=1;n<=9;n++){const g=groupForTable(n),tr=document.createElement("tr");const seat=document.createElement("td");seat.className="seatcell";seat.textContent=n;tr.appendChild(seat);if(g&&!isRepresentative(g,n)){const td=document.createElement("td");td.colSpan=14;td.className="linked-placeholder";td.textContent=g.representative_table+"卓と連結中（"+tableLabel(g)+"）";tr.appendChild(td);body.appendChild(tr);continue}if(!g){const td=document.createElement("td");td.colSpan=14;td.textContent="同期中…";tr.appendChild(td);body.appendChild(tr);continue}const tdRes=document.createElement("td"),inp=document.createElement("input");inp.type="time";inp.className="timeinput";inp.value=g.reservation_time?String(g.reservation_time).slice(0,5):"";inp.onchange=()=>updateReservation(g,inp.value);tdRes.appendChild(inp);tr.appendChild(tdRes);const tdEl=document.createElement("td"),sp=document.createElement("span");sp.className="elapsed"+(twoHour(g)?" danger":"");sp.textContent=elapsedFrom(g.arrival_at);tdEl.appendChild(sp);tr.appendChild(tdEl);for(const [label,col] of STEP_DEFS){const td=document.createElement("td");if(label==="来店"&&isLate(g))td.classList.add("late");if(label==="鍋作り終わり")td.classList.add("milestone30");if(label==="〆の発注")td.classList.add("milestone60");const b=document.createElement("button");b.type="button";b.className="step"+(g[col]?" done":"")+(col==="pot_finish_at"&&potWarn(g)?" warn":"");b.innerHTML="<span>"+labelHtml(label)+"</span>"+(g[col]?"<span class='t'>"+fmtTime(g[col])+"</span>":"");b.onclick=()=>recordStep(g,col);td.appendChild(b);tr.appendChild(td)}const tdN=document.createElement("td"),nb=document.createElement("button");nb.type="button";nb.className="next";nb.textContent="次の組";nb.onclick=()=>nextGroup(g);tdN.appendChild(nb);tr.appendChild(tdN);body.appendChild(tr)}}
function cardClass(g){if(g.checkout_at)return"paid";if(twoHour(g))return"danger";if(isLate(g)||potWarn(g))return"warn";return""}
function renderMobileList(){cardList.innerHTML="";const seen=new Set();for(let n=1;n<=9;n++){const g=groupForTable(n);if(!g||seen.has(g.id))continue;seen.add(g.id);const card=document.createElement("button");card.type="button";card.className="table-card "+cardClass(g);const res=g.reservation_time?String(g.reservation_time).slice(0,5):"—";const el=g.arrival_at?elapsedFrom(g.arrival_at):"";card.innerHTML="<div class='line1'><span class='seat'>"+esc(tableLabel(g))+"</span><span class='meta'>予約 "+esc(res)+(el?"　"+esc(el):"")+"</span></div><div class='current'>現在："+esc(currentAction(g))+"</div>";card.onclick=()=>openDetail(g.id);cardList.appendChild(card)}}
function openDetail(id){currentDetailId=id;document.getElementById("mobileList").style.display="none";document.getElementById("mobileDetail").classList.add("active");renderMobileDetail()}
function closeDetail(){currentDetailId=null;document.getElementById("mobileList").style.display="block";document.getElementById("mobileDetail").classList.remove("active");renderMobileList()}
function renderMobileDetail(){const root=document.getElementById("mobileDetail"),g=groups.find(x=>x.id===currentDetailId);if(!g){closeDetail();return}const linked=g.linked_tables.length>1;root.innerHTML=`<button class="back" id="backBtn">＜ 卓一覧</button><div class="detail-top"><div class="detail-title">${esc(tableLabel(g))}</div><div class="detail-res"><span>予約時間</span><input id="detailReservation" class="timeinput" type="time" value="${g.reservation_time?esc(String(g.reservation_time).slice(0,5)):""}"></div><div class="detail-elapsed ${twoHour(g)?"danger":""}">${esc(elapsedFrom(g.arrival_at))}</div><div class="detail-tools"><button id="detailLinkBtn" class="btn">卓を連結</button>${linked&&!hasService(g)?'<button id="unlinkBtn" class="btn">連結を解除</button>':""}</div></div><div id="stepGrid" class="step-grid"></div><button id="mobileNextBtn" class="mobile-next">次の組</button>`;root.querySelector("#backBtn").onclick=closeDetail;root.querySelector("#detailReservation").onchange=e=>updateReservation(g,e.target.value);root.querySelector("#detailLinkBtn").onclick=()=>openLinkDialog(g.id);if(root.querySelector("#unlinkBtn"))root.querySelector("#unlinkBtn").onclick=()=>unlinkGroup(g);root.querySelector("#mobileNextBtn").onclick=()=>nextGroup(g);const grid=root.querySelector("#stepGrid");for(const [label,col] of STEP_DEFS){const b=document.createElement("button");b.type="button";b.className="mobile-step"+(g[col]?" done":"")+(col==="pot_finish_at"&&potWarn(g)?" warn":"");b.innerHTML="<span>"+esc(label)+"</span>"+(g[col]?"<span class='t'>"+fmtTime(g[col])+"</span>":"");b.onclick=()=>recordStep(g,col);grid.appendChild(b)}}
function renderHistory(){const box=document.getElementById("historyContent");box.innerHTML="";if(!history.length){box.textContent="まだ履歴はありません。";return}for(const h of history){const card=document.createElement("div");card.className="history-card";const res=h.reservation_time?String(h.reservation_time).slice(0,5):"—",arrival=fmtTime(h.arrival_at)||"—",checkout=fmtTime(h.checkout_at)||"—";card.innerHTML=`<button type="button"><div class="history-title">${esc(tableLabel(h))}　予約 ${esc(res)}</div><div class="history-sub">来店 ${esc(arrival)}　→　会計 ${esc(checkout)}</div><div class="history-detail" style="display:none"></div></button>`;const detail=card.querySelector(".history-detail");detail.innerHTML=STEP_DEFS.map(([l,c])=>h[c]?esc(l)+" "+esc(fmtTime(h[c])):"").filter(Boolean).join(" ｜ ")||"記録なし";card.querySelector("button").onclick=()=>detail.style.display=detail.style.display==="none"?"block":"none";box.appendChild(card)}}
function renderAll(){document.getElementById("dateLabel").textContent=dateFmt.format(new Date());renderDesktop();renderMobileList();if(currentDetailId)renderMobileDetail();showConnection()}
async function checkDay(){const now=JST_DATE();if(now===currentDate)return;currentDate=now;groups=[];history=[];currentDetailId=null;localStorage.removeItem(CACHE_KEY);try{await seedIfNeeded();await loadCloud();await subscribeRealtime()}catch{}renderAll()}

document.getElementById("historyBtn").onclick=()=>{renderHistory();document.getElementById("historyDialog").showModal()};
document.getElementById("mobileHistoryBtn").onclick=()=>{renderHistory();document.getElementById("historyDialog").showModal()};
document.getElementById("linkBtn").onclick=()=>openLinkDialog();document.getElementById("resetBtn").onclick=resetToday;document.getElementById("versionBtn").onclick=()=>document.getElementById("versionDialog").showModal();document.getElementById("confirmLinkBtn").onclick=confirmLink;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());window.addEventListener("online",async()=>{showConnection();try{await flushQueue();await loadCloud()}catch{}});window.addEventListener("offline",showConnection);setInterval(()=>{checkDay();renderAll()},1000);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");init();
})();
